# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Hacker's Tale
description: > # this means to ignore newlines until "baseurl:"
  My Journey as a Software Developer
repository: https://github.com/anandsinghkunwar
baseurl:   # the subpath of your site, e.g. /blog
url: https://anandsinghkunwar.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: dark  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Anand Singh Kunwar
email: anandkunwar95[at]gmail.com

navigation:
  - text: Home
    url: /
  - text: Projects
    url: /projects
  - text: Blog
    url: /blog

projects:
  - name: generic-project-1
    description: The first and the most famous project, yet to be decided.
    link: https://anandsinghkunwar.github.io
    image: images/1.jpg
  - name: generic-project-2
    description: A project that almost wasn't a project.
    link: https://anandsinghkunwar.github.io
    image: images/2.jpg
  - name: generic-project-3
    image: images/3.jpg
    description: Penultimate project's generic description that makes no sense at all.
    link: https://anandsinghkunwar.github.io
  - name: generic-project-4
    image: images/4.jpg
    description: An awesome description to describe this final project.
    link: https://anandsinghkunwar.github.io

social:
  - service: github
    username: anandsinghkunwar
    link: https://github.com/anandsinghkunwar
  - service: twitter
    username: anandkunwar
    link: https://twitter.com/anandkunwar

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"
